name 'chef-demo'
maintainer 'Jason Reid'
maintainer_email 'jason.reid@r3labs.io'
license 'all_rights'
description 'Installs/Configures apache2'
long_description 'Installs/Configures apache2'
version '0.0.2'